name: "Flowing Code Commit Message Guidelines"
description: "Ensures that all commit messages are following the Flowing Code Commit Message Guidelines."
runs:
  using: node16
  main: dist/main/index.js
